# Change these first
owner: LinwoodCloud # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Linwood Git
    url: https://git.linwood.dev
  - name: Linwood Drone
    url: https://ci.linwood.dev
  - name: Website
    url: https://linwood.dev
  - name: Dev-Doctor
    url: https://dev-doctor.linwood.dev
  - name: Dev-Doctor Docs
    url: https://docs.dev-doctor.linwood.dev
  - name: Linwood Launch
    url: https://launch.linwood.dev
  - name: Linwood Launch Docs
    url: https://launch.linwood.dev
  - name: Linwood Flow
    url: https://flow.linwood.dev
  - name: Linwood Flow Docs
    url: https://docs.flow.linwood.dev
  - name: GitHub
    url: https://github.com
  - name: Discord
    url: https://discord.com
  - name: Vercel
    url: https://vercel.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.linwood.dev
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/LinwoodCloud/website/blob/main/static/img/Linwood.png?raw=true
  name: Linwood Status
  introTitle: "Linwood Status"
  theme: dark
  introMessage: Here you can find all incidents.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Discord
      href: https://discord.linwood.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
